### ISSUE TITLE
X position in kepler_states.m

### ISSUE THREAD

**Issue by ANDREWNGT** [sammmlow/FORMFLYT#2]
In library/formflyt_orbits/kepler_states.m, line 39, should the x position be calculated as: pos_X=a*(cosd(eccAnom) + e); instead?

Eccentricity should cause the focus to translate in the positive x direction rather than the negative x direction?

**Comment by sammmlow** [comment]
Nope. The focus doesn't move in an ellipse; in fact there isn't any time variance in that equation. If I'm not mistake, turning it from a "-e" to a "+e" merely has the effect of giving you the position with reference to the apogee in the latter case, as compared to the perigee in the former case.

In astrodynamics, the perigee is always used as a reference for the argument of perigee (as its namesake suggests) and the true anomaly, and hence the X-position is always with reference to the perigee.
